// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtigK4Gv2KoMKfrtpD8ETc22C9lljpe8',
    appId: '1:883900645910:web:b799ed86d50ec708ac6b37',
    messagingSenderId: '883900645910',
    projectId: 'classroomproject-cdbd0',
    authDomain: 'classroomproject-cdbd0.firebaseapp.com',
    storageBucket: 'classroomproject-cdbd0.appspot.com',
    measurementId: 'G-65695WG71Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSPQRPRcaesTbwdlZwtyM9jFY_bBTlkc',
    appId: '1:883900645910:android:c15f98e51d294fa6ac6b37',
    messagingSenderId: '883900645910',
    projectId: 'classroomproject-cdbd0',
    storageBucket: 'classroomproject-cdbd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjuH7_8ZOPCKWrCVxC7tyFVf8z63JiFao',
    appId: '1:883900645910:ios:437674c96a969742ac6b37',
    messagingSenderId: '883900645910',
    projectId: 'classroomproject-cdbd0',
    storageBucket: 'classroomproject-cdbd0.appspot.com',
    iosBundleId: 'com.example.classroomproject',
  );
}
